#!/usr/bin/env python3
"""Approach C: Two-Stage Summarization -- vision model describes screenshots.

Stage 1: A vision model receives each screenshot (or consecutive pair) and
describes what is visible and what changed. This produces a text summary
for each step.

Stage 2 (done at evaluation time): The judge receives the instruction plus
all step summaries as text only (no images). This fits in any context window.

Input:
    - Trajectory JSONL (data/standard/agenthorizon.jsonl)
    - Screenshot directory (data/media/images/)

Output:
    - One JSON file per trajectory containing the summarized payload:
      {
        "trajectory_id": str,
        "messages": [...],  # text-only messages for judge
        "step_summaries": [{"step_id": int, "summary": str}, ...],
        "total_steps": int,
        "token_estimate": int,
        "stage1_model": str,
        "stage1_cost_estimate": float  # rough cost of Stage 1 API calls
      }

Usage:
    # Full run with Gemini Flash Lite (cheapest vision model)
    uv run python llm_judges/preprocess_summarize.py \
        --input data/standard/agenthorizon.jsonl \
        --output-dir data/preprocessed/summarize \
        --stage1-provider gemini \
        --stage1-model gemini-2.0-flash-lite \
        --workers 16

    # Test with limit
    uv run python llm_judges/preprocess_summarize.py \
        --input data/standard/agenthorizon.jsonl \
        --output-dir data/preprocessed/summarize \
        --stage1-provider openrouter \
        --stage1-model qwen/qwen-2.5-vl-72b-instruct \
        --limit 3

    # Use batch-size to group consecutive screenshots (saves API calls)
    uv run python llm_judges/preprocess_summarize.py \
        --input data/standard/agenthorizon.jsonl \
        --output-dir data/preprocessed/summarize \
        --stage1-provider gemini \
        --stage1-model gemini-2.0-flash-lite \
        --batch-size 5 \
        --limit 5
"""

import argparse
import asyncio
import functools
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from llm_judges.utils import (
    build_instruction_text,
    estimate_text_tokens,
    format_step_text,
    get_screenshot_path,
    load_api_key,
    load_image_as_base64,
    load_local_image_map,
    load_trajectories,
)

print = functools.partial(print, flush=True)

# Evaluation prompt -- AgentHorizon judge framework, 4-field output schema
EVAL_PROMPT = (
    "You are evaluating a trajectory of an agent performing a computer task. "
    "The trajectory includes:\n"
    "- A Goal describing what the agent was supposed to accomplish\n"
    "- A sequence of Steps showing the actions taken (clicks, typing, key presses, etc.)\n"
    "- Text descriptions of what each screenshot shows (generated by a vision model)\n\n"
    "## Judging framework\n\n"
    "A task has three layers:\n"
    "- **Core Objective** (What + Who): Primary Action + Primary Entity. Changing it -> Critical Mistake.\n"
    "- **Parameters** (When, Which, Where): Scope and data points. Changing them -> Bad Side Effect or Misunderstanding.\n"
    "- **Constraints** (Format, Style): How it looks. Changing them -> Misunderstanding.\n\n"
    "## Mistake types\n"
    "- **Critical Mistake** -- core objective not achieved; user must restart.\n"
    "- **Bad Side Effect** -- goal achieved but with unwanted baggage to delete (>5 min cleanup or external cost).\n"
    "- **Misunderstanding of the Instruction** -- agent took a reasonable action but misinterpreted a detail (<1 min fix).\n\n"
    "## Verdict rule\n"
    "- success = true when all three layers are satisfied.\n"
    "- success = false when any mistake type applies. A Misunderstanding is still a failure.\n\n"
    "## Output\n\n"
    "Be decisive. Respond with a JSON object only:\n"
    "{\n"
    '  "success": true | false,\n'
    '  "reasoning": "1-3 sentences citing which layer (core objective, parameters, or constraints) was or was not satisfied.",\n'
    '  "confidence": "low" | "medium" | "high",\n'
    '  "mistake_type": null when success=true, else one of: "Critical Mistake", "Bad Side Effect", "Misunderstanding of the Instruction"\n'
    "}\n\n"
    "Notes: confidence is evidence strength, not verdict. Low confidence != failure. mistake_type is null on success."
)

# Stage 1 prompt: describe a screenshot or batch of screenshots
STAGE1_SINGLE_PROMPT = """\
Describe what you see in this screenshot of a computer screen. Focus on:
1. Which application/website is open
2. What UI elements are visible (menus, dialogs, text fields, etc.)
3. Any text content that is readable
4. The current state of the interface (loading, error, completed action, etc.)

Be concise but specific. 2-3 sentences max."""

STAGE1_BATCH_PROMPT = """\
These are {n} consecutive screenshots from a computer-use agent performing a task.
For each screenshot, briefly describe:
1. What application/UI is shown
2. What changed from the previous screenshot
3. Key text or UI state visible

Respond as a JSON array of {n} strings, one description per screenshot.
Be concise: 1-2 sentences each."""


async def summarize_single_screenshot(
    screenshot_path: Path,
    step_idx: int,
    action_text: str,
    provider: str,
    model: str,
    api_key: str,
    semaphore: asyncio.Semaphore,
) -> str:
    """Summarize a single screenshot using a vision model."""
    # Load image at moderate resolution (enough for text recognition)
    b64, w, h = load_image_as_base64(screenshot_path, max_width=768, max_height=768, quality=70)

    context = f"Step {step_idx} action: {action_text}"
    prompt = f"{context}\n\n{STAGE1_SINGLE_PROMPT}"

    messages = [
        {
            "role": "user",
            "content": [
                {"type": "text", "text": prompt},
                {
                    "type": "image_url",
                    "image_url": {"url": f"data:image/jpeg;base64,{b64}"},
                },
            ],
        }
    ]

    async with semaphore:
        if provider == "openrouter":
            return await _call_openrouter_vision(messages, model, api_key)
        elif provider == "gemini":
            return await _call_gemini_vision(prompt, b64, model, api_key)
        else:
            raise ValueError(f"Unknown provider: {provider}")


async def summarize_screenshot_batch(
    screenshot_paths: list[tuple[Path, int, str]],  # (path, step_idx, action_text)
    provider: str,
    model: str,
    api_key: str,
    semaphore: asyncio.Semaphore,
) -> list[str]:
    """Summarize a batch of consecutive screenshots in a single API call."""
    n = len(screenshot_paths)

    content_parts = []
    actions_text = []
    for path, step_idx, action_text in screenshot_paths:
        actions_text.append(f"Step {step_idx}: {action_text}")
        b64, w, h = load_image_as_base64(path, max_width=512, max_height=512, quality=60)
        content_parts.append({
            "type": "image_url",
            "image_url": {"url": f"data:image/jpeg;base64,{b64}"},
        })

    prompt = (
        "Actions performed:\n" + "\n".join(actions_text) + "\n\n"
        + STAGE1_BATCH_PROMPT.format(n=n)
    )
    content_parts.insert(0, {"type": "text", "text": prompt})

    messages = [{"role": "user", "content": content_parts}]

    async with semaphore:
        if provider == "openrouter":
            response = await _call_openrouter_vision(messages, model, api_key)
        elif provider == "gemini":
            # For Gemini batch, use all images
            response = await _call_gemini_vision_batch(prompt, screenshot_paths, model, api_key)
        else:
            raise ValueError(f"Unknown provider: {provider}")

    # Parse batch response
    response = response.strip()
    response = re.sub(r"^```(?:json)?\s*\n?", "", response)
    response = re.sub(r"\n?```\s*$", "", response)
    try:
        summaries = json.loads(response)
        if isinstance(summaries, list) and len(summaries) == n:
            return [str(s) for s in summaries]
    except json.JSONDecodeError:
        pass

    # Fallback: split by lines or just repeat the whole response
    lines = [l.strip() for l in response.split("\n") if l.strip()]
    if len(lines) >= n:
        return lines[:n]
    return [response] * n


async def _call_openrouter_vision(messages: list[dict], model: str, api_key: str) -> str:
    """Call OpenRouter API with vision content."""
    import aiohttp

    payload = {
        "model": model,
        "messages": messages,
        "temperature": 0,
        "max_tokens": 300,
    }

    async with aiohttp.ClientSession() as session:
        async with session.post(
            "https://openrouter.ai/api/v1/chat/completions",
            json=payload,
            headers={
                "Authorization": f"Bearer {api_key}",
                "Content-Type": "application/json",
            },
            timeout=aiohttp.ClientTimeout(total=120),
        ) as resp:
            data = await resp.json()
            if resp.status != 200:
                raise RuntimeError(f"OpenRouter API error {resp.status}: {data}")
            return data["choices"][0]["message"]["content"] or ""


async def _call_gemini_vision(prompt: str, image_b64: str, model: str, api_key: str) -> str:
    """Call Gemini API with a single image."""
    import base64
    from google import genai
    from google.genai import types

    client = genai.Client(api_key=api_key)
    image_bytes = base64.b64decode(image_b64)

    loop = asyncio.get_event_loop()
    response = await loop.run_in_executor(
        None,
        lambda: client.models.generate_content(
            model=model,
            contents=[
                types.Content(
                    parts=[
                        types.Part.from_text(text=prompt),
                        types.Part.from_bytes(data=image_bytes, mime_type="image/jpeg"),
                    ],
                ),
            ],
            config=types.GenerateContentConfig(
                temperature=0,
                max_output_tokens=300,
            ),
        ),
    )
    return response.text or ""


async def _call_gemini_vision_batch(
    prompt: str,
    screenshot_paths: list[tuple[Path, int, str]],
    model: str,
    api_key: str,
) -> str:
    """Call Gemini API with multiple images."""
    import base64
    from google import genai
    from google.genai import types

    client = genai.Client(api_key=api_key)

    parts = [types.Part.from_text(text=prompt)]
    for path, step_idx, action_text in screenshot_paths:
        b64, w, h = load_image_as_base64(path, max_width=512, max_height=512, quality=60)
        image_bytes = base64.b64decode(b64)
        parts.append(types.Part.from_bytes(data=image_bytes, mime_type="image/jpeg"))

    loop = asyncio.get_event_loop()
    response = await loop.run_in_executor(
        None,
        lambda: client.models.generate_content(
            model=model,
            contents=[types.Content(parts=parts)],
            config=types.GenerateContentConfig(
                temperature=0,
                max_output_tokens=300 * len(screenshot_paths),
            ),
        ),
    )
    return response.text or ""


def build_summarized_payload(
    trajectory: dict,
    step_summaries: dict[int, str],
) -> dict:
    """Build the Stage 2 text-only payload from step summaries.

    Returns the messages payload ready for the judge API call.
    """
    instruction = build_instruction_text(trajectory)
    steps = trajectory.get("steps", [])

    # Build text-only trajectory with visual descriptions
    step_texts = []
    for i, step in enumerate(steps):
        step_text = format_step_text(step, i)
        summary = step_summaries.get(i, "")
        if summary:
            step_text += f"\n**Screenshot description:** {summary}"
        step_texts.append(step_text)

    trajectory_text = (
        f"## Goal\n\n{instruction}\n\n"
        f"## Steps\n\nTotal steps: **{len(steps)}**\n"
        f"(Each step includes a text description of the screenshot)\n\n"
        + "\n\n".join(step_texts)
    )

    token_estimate = estimate_text_tokens(EVAL_PROMPT) + estimate_text_tokens(trajectory_text)

    messages = [
        {"role": "system", "content": EVAL_PROMPT},
        {"role": "user", "content": trajectory_text},
    ]

    return {
        "messages": messages,
        "token_estimate": token_estimate,
    }


async def process_one(
    trajectory: dict,
    index: int,
    total: int,
    provider: str,
    model: str,
    api_key: str,
    base_dir: Path,
    output_dir: Path | None,
    batch_size: int,
    semaphore: asyncio.Semaphore,
    local_image_id: str | None = None,
) -> dict:
    """Process a single trajectory: summarize all screenshots, build payload."""
    tid = trajectory["trajectory_id"]
    steps = trajectory.get("steps", [])

    # Check for existing output (resumability)
    if output_dir is not None:
        out_path = output_dir / f"{tid}.json"
        if out_path.exists():
            print(f"[{index}/{total}] [SKIP] {tid[:12]}...")
            return json.loads(out_path.read_text())

    # Collect screenshots that exist
    screenshot_info = []  # (step_idx, path, action_text)
    for i, step in enumerate(steps):
        path = get_screenshot_path(step, base_dir, local_image_id=local_image_id)
        if path is not None:
            action = step.get("action", {})
            action_type = action.get("type", "unknown")
            params = action.get("parameters", {})
            if action_type == "click":
                action_text = f'{params.get("button", "left")}-click ({params.get("x",0)}, {params.get("y",0)})'
            elif action_type == "type":
                action_text = f'type "{params.get("text", "")}"'
            elif action_type == "key":
                action_text = f'key "{params.get("key", "")}"'
            else:
                action_text = f'{action_type}'
            screenshot_info.append((i, path, action_text))

    # Summarize screenshots
    step_summaries = {}

    if batch_size == 1:
        # Individual summaries (more accurate, more API calls)
        tasks = []
        for step_idx, path, action_text in screenshot_info:
            tasks.append(
                summarize_single_screenshot(
                    path, step_idx, action_text, provider, model, api_key, semaphore
                )
            )
        results = await asyncio.gather(*tasks, return_exceptions=True)
        for (step_idx, _, _), result in zip(screenshot_info, results):
            if isinstance(result, Exception):
                step_summaries[step_idx] = f"[Error: {result}]"
            else:
                step_summaries[step_idx] = result
    else:
        # Batch summaries (fewer API calls)
        for batch_start in range(0, len(screenshot_info), batch_size):
            batch = screenshot_info[batch_start : batch_start + batch_size]
            batch_paths = [(path, idx, action_text) for idx, path, action_text in batch]
            try:
                summaries = await summarize_screenshot_batch(
                    batch_paths, provider, model, api_key, semaphore
                )
                for (step_idx, _, _), summary in zip(batch, summaries):
                    step_summaries[step_idx] = summary
            except Exception as e:
                for step_idx, _, _ in batch:
                    step_summaries[step_idx] = f"[Error: {e}]"

    # Build Stage 2 payload
    payload = build_summarized_payload(trajectory, step_summaries)

    result = {
        "trajectory_id": tid,
        "messages": payload["messages"],
        "step_summaries": [
            {"step_id": k, "summary": v}
            for k, v in sorted(step_summaries.items())
        ],
        "total_steps": len(steps),
        "token_estimate": payload["token_estimate"],
        "stage1_model": f"{provider}/{model}",
        "num_screenshots_summarized": len(step_summaries),
    }

    print(
        f"[{index}/{total}] {tid[:12]}... "
        f"steps={len(steps)} summarized={len(step_summaries)} "
        f"tokens~{payload['token_estimate']}"
    )

    if output_dir is not None:
        out_path = output_dir / f"{tid}.json"
        out_path.write_text(json.dumps(result, indent=None) + "\n")

    return result


async def run(args: argparse.Namespace) -> None:
    base_dir = Path(args.base_dir)
    output_dir = Path(args.output_dir) if args.output_dir else None
    if output_dir:
        output_dir.mkdir(parents=True, exist_ok=True)

    trajectories = load_trajectories(args.input, limit=args.limit)
    print(f"Loaded {len(trajectories)} trajectories")
    image_map = load_local_image_map(args.labels)
    print(f"Loaded local_image_id mapping for {len(image_map)} trajectories from {args.labels}")
    print(f"Stage 1 model: {args.stage1_provider}/{args.stage1_model}")
    print(f"Batch size: {args.batch_size}")
    print(f"Workers: {args.workers}")
    print()

    key_name = {
        "openrouter": "OPENROUTER_API_KEY",
        "gemini": "GEMINI_API_KEY",
    }[args.stage1_provider]
    api_key = load_api_key(key_name)

    semaphore = asyncio.Semaphore(args.workers)
    total = len(trajectories)

    # Process sequentially to avoid overwhelming the API
    # (each trajectory already parallelizes its screenshot summarizations)
    results = []
    for i, traj in enumerate(trajectories):
        result = await process_one(
            trajectory=traj,
            index=i + 1,
            total=total,
            provider=args.stage1_provider,
            model=args.stage1_model,
            api_key=api_key,
            base_dir=base_dir,
            output_dir=output_dir,
            batch_size=args.batch_size,
            semaphore=semaphore,
            local_image_id=image_map.get(traj["trajectory_id"]),
        )
        results.append(result)

    # Summary
    token_counts = [r["token_estimate"] for r in results]
    print()
    print("=== Summary ===")
    if token_counts:
        import statistics
        print(f"Token estimates: mean={statistics.mean(token_counts):.0f}, "
              f"median={statistics.median(token_counts):.0f}, "
              f"max={max(token_counts):.0f}")
        total_screenshots = sum(r.get("num_screenshots_summarized", 0) for r in results)
        print(f"Total screenshots summarized: {total_screenshots}")
        # Rough Stage 1 cost estimate
        # ~500 input tokens per screenshot + 100 output tokens
        cost_per_screenshot = 500 * 0.10 / 1e6 + 100 * 0.30 / 1e6  # Flash Lite pricing
        print(f"Est. Stage 1 cost (Flash Lite): ${total_screenshots * cost_per_screenshot:.2f}")


def main():
    parser = argparse.ArgumentParser(
        description="Approach C: Two-stage summarization -- vision model describes screenshots."
    )
    parser.add_argument("--input", required=True, help="Path to trajectory JSONL")
    parser.add_argument(
        "--labels", default="data/standard/agenthorizon_labels.jsonl",
        help="Labels JSONL for trajectory_id -> original_id mapping (used only for "
             "screenshot path resolution; verdict fields are never read).",
    )
    parser.add_argument("--output-dir", default=None, help="Output directory")
    parser.add_argument("--base-dir", default=".", help="Base dir for screenshot paths")
    parser.add_argument("--stage1-provider", default="gemini", choices=["openrouter", "gemini"])
    parser.add_argument("--stage1-model", default="gemini-2.0-flash-lite",
                        help="Vision model for Stage 1 summarization")
    parser.add_argument("--batch-size", type=int, default=1,
                        help="Screenshots per API call (1=individual, >1=batch)")
    parser.add_argument("--workers", type=int, default=8,
                        help="Concurrent Stage 1 API calls")
    parser.add_argument("--limit", type=int, default=None, help="Process first N only")
    args = parser.parse_args()

    asyncio.run(run(args))


if __name__ == "__main__":
    main()
